#!/usr/bin/env bash
#install and setup haproxy on an ubuntu machine

#Update package list and install haproxy
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
-y
sudo add-apt-repository ppa:vbernat/haproxy-2.7
-y
sudo apt-get install haproxy=2.7.\*
-y
#enable haproxy init script

#configure the haproxy to forward requests to my two servers using the round-robin algorithm
echo "


#my config
frontend web-frontend
        mode http
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 100804-web-01 100.26.165.61:80 check
        server 100804-web-02 100.25.47.254:80 check
" >> /etc/haproxy/haproxy.cfg

#restart haproxy
service haproxy restart
