#!/usr/bin/env bash
#install and setup haproxy on an ubuntu machine

#Update package list and install haproxy
apt-get update
apt-get -y install haproxy

#enable haproxy init script

#configure the haproxy to forward requests to my two servers using the round-robin algorithm
echo "


#my config
frontend web-frontend
        mode tcp
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 100804-web-01 100.26.165.61:80 check
        server 100804-web-02 100.25.47.254:80 check
" >> /etc/haproxy/haproxy.cfg

#restart haproxy
service haproxy restart
