#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown -R "$USER:$USER" /etc/haproxy/

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
server_config=\
"

#configure the haproxy configuration file to distribute requests using a roundrobin algorithm
server_config=\
"

frontend web-frontend
        mode http
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 100804-web-01 100.26.165.61:80 check
        server 100804-web-02 100.25.47.254:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAproxy service
sudo service haproxy restart
